import type { Metadata } from 'next'
import { Inter, Andada_Pro } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from "./components/Footer"

const inter = Inter({ subsets: ['latin'] })
const andada_pro = Andada_Pro({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={andada_pro.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
